/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MailRouteImport } from './routes/mail'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as BeadsRouteImport } from './routes/beads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormulasIndexRouteImport } from './routes/formulas.index'
import { Route as SessionsNameRouteImport } from './routes/sessions.$name'
import { Route as GcSplatRouteImport } from './routes/gc.$'
import { Route as FormulasNameRouteImport } from './routes/formulas.$name'
import { Route as ApiPtyRouteImport } from './routes/api/pty'

const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const BeadsRoute = BeadsRouteImport.update({
  id: '/beads',
  path: '/beads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasIndexRoute = FormulasIndexRouteImport.update({
  id: '/formulas/',
  path: '/formulas/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsNameRoute = SessionsNameRouteImport.update({
  id: '/sessions/$name',
  path: '/sessions/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const GcSplatRoute = GcSplatRouteImport.update({
  id: '/gc/$',
  path: '/gc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasNameRoute = FormulasNameRouteImport.update({
  id: '/formulas/$name',
  path: '/formulas/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtyRoute = ApiPtyRouteImport.update({
  id: '/api/pty',
  path: '/api/pty',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/cities': typeof CitiesRoute
  '/endpoints': typeof EndpointsRoute
  '/mail': typeof MailRoute
  '/orders': typeof OrdersRoute
  '/packs': typeof PacksRoute
  '/api/pty': typeof ApiPtyRoute
  '/formulas/$name': typeof FormulasNameRoute
  '/gc/$': typeof GcSplatRoute
  '/sessions/$name': typeof SessionsNameRoute
  '/formulas/': typeof FormulasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/cities': typeof CitiesRoute
  '/endpoints': typeof EndpointsRoute
  '/mail': typeof MailRoute
  '/orders': typeof OrdersRoute
  '/packs': typeof PacksRoute
  '/api/pty': typeof ApiPtyRoute
  '/formulas/$name': typeof FormulasNameRoute
  '/gc/$': typeof GcSplatRoute
  '/sessions/$name': typeof SessionsNameRoute
  '/formulas': typeof FormulasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/cities': typeof CitiesRoute
  '/endpoints': typeof EndpointsRoute
  '/mail': typeof MailRoute
  '/orders': typeof OrdersRoute
  '/packs': typeof PacksRoute
  '/api/pty': typeof ApiPtyRoute
  '/formulas/$name': typeof FormulasNameRoute
  '/gc/$': typeof GcSplatRoute
  '/sessions/$name': typeof SessionsNameRoute
  '/formulas/': typeof FormulasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beads'
    | '/cities'
    | '/endpoints'
    | '/mail'
    | '/orders'
    | '/packs'
    | '/api/pty'
    | '/formulas/$name'
    | '/gc/$'
    | '/sessions/$name'
    | '/formulas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beads'
    | '/cities'
    | '/endpoints'
    | '/mail'
    | '/orders'
    | '/packs'
    | '/api/pty'
    | '/formulas/$name'
    | '/gc/$'
    | '/sessions/$name'
    | '/formulas'
  id:
    | '__root__'
    | '/'
    | '/beads'
    | '/cities'
    | '/endpoints'
    | '/mail'
    | '/orders'
    | '/packs'
    | '/api/pty'
    | '/formulas/$name'
    | '/gc/$'
    | '/sessions/$name'
    | '/formulas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeadsRoute: typeof BeadsRoute
  CitiesRoute: typeof CitiesRoute
  EndpointsRoute: typeof EndpointsRoute
  MailRoute: typeof MailRoute
  OrdersRoute: typeof OrdersRoute
  PacksRoute: typeof PacksRoute
  ApiPtyRoute: typeof ApiPtyRoute
  FormulasNameRoute: typeof FormulasNameRoute
  GcSplatRoute: typeof GcSplatRoute
  SessionsNameRoute: typeof SessionsNameRoute
  FormulasIndexRoute: typeof FormulasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beads': {
      id: '/beads'
      path: '/beads'
      fullPath: '/beads'
      preLoaderRoute: typeof BeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas/': {
      id: '/formulas/'
      path: '/formulas'
      fullPath: '/formulas/'
      preLoaderRoute: typeof FormulasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$name': {
      id: '/sessions/$name'
      path: '/sessions/$name'
      fullPath: '/sessions/$name'
      preLoaderRoute: typeof SessionsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gc/$': {
      id: '/gc/$'
      path: '/gc/$'
      fullPath: '/gc/$'
      preLoaderRoute: typeof GcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas/$name': {
      id: '/formulas/$name'
      path: '/formulas/$name'
      fullPath: '/formulas/$name'
      preLoaderRoute: typeof FormulasNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pty': {
      id: '/api/pty'
      path: '/api/pty'
      fullPath: '/api/pty'
      preLoaderRoute: typeof ApiPtyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeadsRoute: BeadsRoute,
  CitiesRoute: CitiesRoute,
  EndpointsRoute: EndpointsRoute,
  MailRoute: MailRoute,
  OrdersRoute: OrdersRoute,
  PacksRoute: PacksRoute,
  ApiPtyRoute: ApiPtyRoute,
  FormulasNameRoute: FormulasNameRoute,
  GcSplatRoute: GcSplatRoute,
  SessionsNameRoute: SessionsNameRoute,
  FormulasIndexRoute: FormulasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
